### ISSUE TITLE
Problems running with typescript

### ISSUE THREAD

**Issue by marcoturi** [artberri/rollup-plugin-istanbul#13]
Hi @artberri and thank you for your plugin. I'm having a similar issue of #6 , but with typescript. Here is the code i use:

https://github.com/hotforfeature/ionic2-boilerplate/blob/master/config/karma.conf.js

I can't put rollup-plugin-istanbul before rollup-plugin-typescript otherwise I get:

```
Error: Line 4: Unexpected token ILLEGAL
    at constructError (/Users/marco/Sources/Github/ionic2-boilerplate/node_modules/istanbul/node_modules/esprima/esprima.js:2407:21)
    at createError (/Users/marco/Sources/Github/ionic2-boilerplate/node_modules/istanbul/node_modules/esprima/esprima.js:2426:17)
    at unexpectedTokenError (/Users/marco/Sources/Github/ionic2-boilerplate/node_modules/istanbul/node_modules/esprima/esprima.js:2501:13)
    at throwUnexpectedToken (/Users/marco/Sources/Github/ionic2-boilerplate/node_modules/istanbul/node_modules/esprima/esprima.js:2505:15)
    at scanPunctuator (/Users/marco/Sources/Github/ionic2-boilerplate/node_modules/istanbul/node_modules/esprima/esprima.js:842:13)
    at advance (/Users/marco/Sources/Github/ionic2-boilerplate/node_modules/istanbul/node_modules/esprima/esprima.js:1622:16)
    at lex (/Users/marco/Sources/Github/ionic2-boilerplate/node_modules/istanbul/node_modules/esprima/esprima.js:1691:78)
    at consumeSemicolon (/Users/marco/Sources/Github/ionic2-boilerplate/node_modules/istanbul/node_modules/esprima/esprima.js:2606:13)
    at parseImportDeclaration (/Users/marco/Sources/Github/ionic2-boilerplate/node_modules/istanbul/node_modules/esprima/esprima.js:5455:9)
    at parseStatementListItem (/Users/marco/Sources/Github/ionic2-boilerplate/node_modules/istanbul/node_modules/esprima/esprima.js:3975:24)
    at parseScriptBody (/Users/marco/Sources/Github/ionic2-boilerplate/node_modules/istanbul/node_modules/esprima/esprima.js:5490:25)
    at parseProgram (/Users/marco/Sources/Github/ionic2-boilerplate/node_modules/istanbul/node_modules/esprima/esprima.js:5506:16)
    at Object.parse (/Users/marco/Sources/Github/ionic2-boilerplate/node_modules/istanbul/node_modules/esprima/esprima.js:5690:23)
    at Object.instrumentSync (/Users/marco/Sources/Github/ionic2-boilerplate/node_modules/istanbul/lib/instrumenter.js:459:31)
    at Object.transform (/Users/marco/Sources/Github/ionic2-boilerplate/node_modules/rollup-plugin-istanbul/dist/rollup-plugin-istanbul.cjs.js:28:27)
    at /Users/marco/Sources/Github/ionic2-boilerplate/node_modules/rollup/src/utils/transform.js:19:35

```

At the same time i get the istanbul/lib/report/html.js:241:45 error of #6 if i keep the plugin after the others. For further info https://github.com/marcoturi/ionic2-boilerplate/issues/5

**Comment by joaovieira** [comment]
Can't get this to work with Typescript as well.

When not using Istanbul plugin, the sourcemaps are loaded correctly for all files in the bundle. 

![screen shot 2016-12-01 at 15 01 55 2](https://cloud.githubusercontent.com/assets/474603/20800457/7ecfdc16-b7dd-11e6-839a-65c51fc23437.png)

With istanbul, the instrumented files "loose" their mapping.

![screen shot 2016-12-01 at 15 34 59 2](https://cloud.githubusercontent.com/assets/474603/20800547/c757dcea-b7dd-11e6-8510-647cac0489bf.png)

Not sure this should happen already in the first place, but then the coverage report gets the wrong lines as mentioned in marcoturi/ionic2-boilerplate#5

![screen shot 2016-12-01 at 15 37 13](https://cloud.githubusercontent.com/assets/474603/20800581/e21d7e90-b7dd-11e6-8af6-8ade32b7c0f0.png)

The plugin is instrumenting the transpiled and bundled code. The instrumented parts point to the original file (TS), but somehow seem to actually map the intermediary transpiled (`foo.js`) file?

intermediary `foo.js`:
```javascript
export function foo() {
    return 1;
}
export function bar(smt) {
    return smt === 'foo';
}
```

`tsconfig.json`:
```javascript
{
  "compilerOptions": {
    "target": "es6",
    "moduleResolution": "node",
    "declaration": true,
    "sourceMap": true
  }
}
```

`karma.config.js`:
```javascript
const node = require('rollup-plugin-node-resolve')
const tsc = require('rollup-plugin-typescript')
const typescript = require('typescript')
const istanbul = require('rollup-plugin-istanbul')

const TESTS = 'test.ts'
const EXTERNAL = 'node_modules/**/*'

module.exports = function (config) {
  config.set({
    frameworks: ['jasmine'],
    files: [ TESTS ],
    preprocessors: {
      [TESTS]: ['rollup']
    },
    rollupPreprocessor: {
      plugins: [
        tsc({typescript}),
        node({ jsnext: true }),
        istanbul({
          exclude: [TESTS, EXTERNAL]
        })
      ],
      format: 'iife',
      sourceMap: 'inline'
    },
    reporters: ['coverage'],
    browsers: ['Chrome'],
    singleRun: true
  })
}
```

I've tried to compile TS before running Karma, having sourcemaps available for remap-istanbul but to no success or little success.

**Comment by jlmakes** [comment]
@joaovieira I had a similar issue, where line numbers were not accurate; I solved that by using:
```js
instrumenterConfig: {
    embedSource: true
}
```
Not sure if that's any help.

**Comment by jlmakes** [comment]
@marcoturi @joaovieira 

Can you try my fork to see if `TypeError: Cannot read property 'text' of undefined` goes away?
https://github.com/jlmakes/rollup-plugin-istanbul

**Comment by artberri** [comment]
Sorry for being late answering here.

The new v2.0.0 version uses now the new istanbul instrumenter. Please double check if you keep suffering the error.
